### ISSUE TITLE
Tweaks to suggested citation formatting

### ISSUE THREAD

**Issue by dhimmel** [dhimmel/het.io#32]
Currently, https://het.io/about/#cite looks like:

> ![image](https://user-images.githubusercontent.com/1117703/63615710-f7e04a00-c5b3-11e9-8386-705d5e0a7174.png)

It would be great if we could add the additional PMID and PMCID identifiers, since they are often helpful for people wanting to cite these works. You can find all three identifiers and the suggested formatting in the `manubot cite` output below:

```
manubot cite doi:10.7554/eLife.26726 doi:10.1371/journal.pcbi.1004259 --format=html --render
```

```html
<div id="refs" class="references" role="doc-bibliography">
<div id="ref-O21tn8vf">
<p>1. <strong>Systematic integration of biomedical knowledge prioritizes drugs for repurposing</strong><br />
Daniel Scott Himmelstein, Antoine Lizee, Christine Hessler, Leo Brueggeman, Sabrina L Chen, Dexter Hadley, Ari Green, Pouya Khankhanian, Sergio E Baranzini<br />
<em>eLife</em> (2017-09-22) <a href="https://doi.org/cdfk">https://doi.org/cdfk</a><br />
DOI: <a href="https://doi.org/10.7554/elife.26726">10.7554/elife.26726</a> · PMID: <a href="https://www.ncbi.nlm.nih.gov/pubmed/28936969">28936969</a> · PMCID: <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5640425">PMC5640425</a></p>
</div>
<div id="ref-WkPlH1ds">
<p>2. <strong>Heterogeneous Network Edge Prediction: A Data Integration Approach to Prioritize Disease-Associated Genes</strong><br />
Daniel S. Himmelstein, Sergio E. Baranzini<br />
<em>PLOS Computational Biology</em> (2015-07-09) <a href="https://doi.org/98q">https://doi.org/98q</a><br />
DOI: <a href="https://doi.org/10.1371/journal.pcbi.1004259">10.1371/journal.pcbi.1004259</a> · PMID: <a href="https://www.ncbi.nlm.nih.gov/pubmed/26158728">26158728</a> · PMCID: <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4497619">PMC4497619</a></p>
</div>
</div>
```

**Comment by dhimmel** [comment]
I'm also thinking it may be good mention the publications at https://het.io/studies/

> ![image](https://user-images.githubusercontent.com/1117703/63615890-61605880-c5b4-11e9-8157-59433dd53d3e.png)

Would something like:

+ Results from Himmelstein et al (2017) _eLife_
+ Results from Himmelstein et al (2015) _PLOS Computational Biology_

help readers immediately know what the studies corresponded to?

I think we also probably want to add the citations (or abbreviated versions) to:

+ https://het.io/repurpose/
+ https://het.io/disease-genes/

Since redirecting to "Cite these results" doesn't show which study it actually is.

**Comment by dhimmel** [comment]
Should we add title/tooltip text to "Read the Paper" with the paper title and journal info?

**Comment by vincerubinetti** [comment]
> Since redirecting to "Cite these results" doesn't show which study it actually is.

What if we split up that "Cite" section on the "About" page into two sections for each paper, and then we can link directly to which one it is.

**Comment by dhimmel** [comment]
I think the solution in https://github.com/hetio/het.io/pull/37 works for me
