### ISSUE TITLE
Change "relationships" to "edges"

### ISSUE THREAD

**Issue by dhimmel** [dhimmel/het.io#33]
I'll comment below with any tooltip tweaks we should make

**Comment by dhimmel** [comment]
At https://hetio.github.io/repurpose-frontend/?tab=diseases&id=DOID_2841

![image](https://user-images.githubusercontent.com/1117703/63618051-109f2e80-c5b9-11e9-87a7-7927fcc96c81.png)

Highlighted term should be "edges" not "relationships" for consistency with other tables.

Also effects https://hetio.github.io/repurpose-frontend/?tab=compounds&id=DB01048

**Comment by dhimmel** [comment]
https://hetio.github.io/repurpose-frontend/?tab=metapaths only has 121 rows, but should have many more (1206). My guess is that all rows with a missing coefficient have been filtered out?

**Comment by vincerubinetti** [comment]
> https://hetio.github.io/repurpose-frontend/?tab=metapaths only has 121 rows, but should have many more (1206). My guess is that all rows with a missing coefficient have been filtered out?

121 is the number of pages, not number rows. So that means there are at least 1210 rows. The number of rows is shown in the upper left corner:

![image](https://user-images.githubusercontent.com/8326331/63694036-8c7cbf00-c7e3-11e9-8004-99c75478ed96.png)

**Comment by dhimmel** [comment]
> The number of rows is shown in the upper left corner:

Ah got it. The metapaths table has the right number of entries, but it looks like the null coefficients are getting set to `0.000`. They should remain blank because they are distinct from the actual zeros.

**Comment by vincerubinetti** [comment]
Closed by https://github.com/hetio/repurpose-frontend/pull/20
