### ISSUE TITLE
Typo "Biologic Class" in metagraph

### ISSUE THREAD

**Issue by dhimmel** [dhimmel/het.io#36]
typo in `about/metagraph.png`:

> ![](https://github.com/hetio/het.io/raw/e1ca4fd591e0aa01a3767bbf5597a910528f6f86/about/metagraph.png)

Should be "Biological Process" not "Biologic Class". There are several other versions of this image at https://github.com/hetio/het.io/tree/gh-pages/about.

@vincerubinetti do we still have the source for this image and would this be fixable?

**Comment by vincerubinetti** [comment]
[metagraph.zip](https://github.com/hetio/het.io/files/4816796/metagraph.zip)

**Comment by dhimmel** [comment]
Those look good. Do you want to go ahead and commit them to this repo?

Also remind me what the source is... i.e. how this was generated and whether we have that source file tracked anywhere?

**Comment by vincerubinetti** [comment]
I'll commit this change when I fix the other issues with the site. Have been having problems today trying to get ruby and jekyll to build the site locally on my Windows machine, but I'll still have it ready for you to review tomorrow.

The source is in my google drive. It's a "diagrams.net" (originally "draw.io"?) document:
![image](https://user-images.githubusercontent.com/8326331/85356220-6f388000-b4dc-11ea-86a9-523bd468ab96.png)

Here is the document in my google drive:
https://drive.google.com/file/d/1E1Cku_gYtHHIe-lvenULVUo-gNucqNWZ/view?usp=sharing

I'll include the draw.io (which I just now figured out how to save), svg, and png versions in the commit to the website.

**Comment by vincerubinetti** [comment]
[metagraph.zip](https://github.com/hetio/het.io/files/4816946/metagraph.zip)
