### ISSUE TITLE
Favicon tweaks

### ISSUE THREAD

**Issue by vincerubinetti** [dhimmel/het.io#5]
- [x] Remove rounded edges from favicon to match non-rounded aesthetic of everything else on the site and in hetmech.

- [x] Also, look into why the correct favicon isn't showing up when linking the site in slack. ~Maybe `favicon.ico` (legacy format) is actually needed. If so, we should try to only use a favicon with a 512x512, so chrome does not show lowest 16x16 resolution variant by default, which looks crappy on high dpi/retina displays.~ Edit: maybe it's just because I'm temporarily hosting it on vincentrubinetti.com/hetio, and there's already a higher level favicon in the root of vincentrubinetti.com that takes precedence?

**Comment by dhimmel** [comment]
Currently, this is the [favicon file](https://github.com/hetio/het.io/blob/c1e64713616ccd761e66fbaa8232a2b28aa6171f/favicon.ico). Feel free to change it or remake it however you see fit.
